### ISSUE TITLE
Version 1.0.0 doesn't allow adding custom devices or other displays

### ISSUE THREAD

**Issue by murad-alm** [elral/MF_FCU_EFIS_OLEDs#18]
Hello again,
apologies for the constant issues.. I'm not sure if this is a bug tbh.. 

Adding custom devices it not possible. The only way to add an I2C display is by using the "upload board's default config" button. Even after uploading the config. the device still shows a warning that the modifications will be lost, as if it didn't upload them to the board.
![image](https://github.com/user-attachments/assets/d6baa120-d065-4d9b-89b7-651be43bab53)

Furthermore, version 0.9.2 allowed me to add other displays (i.e. 7-segs) while version 1.0.0 shows the following error when trying to change the display type from MAX7291 to TM163. 
![image](https://github.com/user-attachments/assets/4480b729-2ef9-4d65-8c1a-a801d20e0a37)

Is this a limitation or an actual bug? 

I apologize if this isn't an issue. Appreciate your help!

**Comment by elral** [comment]
Hi @murad-alm,
the first topic, still showing the warning even after uploading, is a known bug from the connector.

The other problems shouldn't happen, I have to investigate what is going on.
Could you please check which type is shown for the board (click on the board an make a screenshot)?

**Comment by elral** [comment]
OK, it's a bug in the connector. Everything below FW version 1.0.0 or above 2.5.0 is working fine. For custom devices the wrong FW version is checked. We had a similiar topic in the last weeks, but wasn't solved in the end. I will contact Neil and/or Sebastian.

Short term solution would be to use version 0.9.2 and modifying the `gagagu_fcu_efis_mega.board.json` file by adding `"TimeoutForFirmwareUpdate": 25000` 
![image](https://github.com/user-attachments/assets/4ec5afd1-24b4-419f-a0c1-2cafcc5bfed6)
This prevents the timeout error.

All existing files from this project has to be deleted before using the old version, otherwise it might be that the files do not fit together.

Sorry for this, wasn't aware that this can happen with version >= 1.0.0

**Comment by murad-alm** [comment]
Hi @elral ,
Thank you again for your help. I will fall back to v0.9.2. Here is a screenshot of my board:
![image](https://github.com/user-attachments/assets/d83d55f3-29e0-48a6-9218-39bd5ecbdf08)
I'm also using Connector v10.4.0

On another matter: Do I have to use 7 displays for this project to work? Currently I'm using only 3 (for test purposes) and only one of them is working. Please note that I only added one display as a custom device and assigned everything to it. So I was wondering if I had to connect all 7 displays to make it work  (If you would like to, we can setup a Discord call). 
Here are some screenshots of the setup:
![image](https://github.com/user-attachments/assets/ab99ec66-8525-4184-af8f-ecd81aa15322)

![image](https://github.com/user-attachments/assets/7d6666d4-2569-48f1-974d-3a7b74d7d9b7)
In this case only one display shows QNH 1019 while the other one is turned off.

The 3 displays are connected to the multiplexer on SC0-SD0 / SC1-SD1 / SD2-SC2 but only one is working. If I swap the cables, the other ones would work (all displays are functioning). I thought I should ask you if my setup is wrong before buying another multiplexer to check if it is the source of this issue.


Final note: Do you have any payment methods (PayPal or something) to support this project? I would like to buy you a cup of coffee. I really appreciate your work and your support and I feel bad for bothering you the whole time with my issues..

**Comment by elral** [comment]
Hi @murad-alm,
defining one custom deviceand defining everything to this one is OK. And only two connected should also work. But best would be only having configs which writes to the existing ones, otherwise there is a time delay coming from an I2C bus timeout.

The configs are created from Gagagu who did the main work for this project. If there any questions in this regard it would be the best to ask on the Mobiflight discord server. Also for further questions you can contact me on discord, it's a little bit easier for me to keep on track,

@DocMoebiuz has implemented a "Donate" button for the project within the connector ;)
![image](https://github.com/user-attachments/assets/95c62d25-d297-433a-ac25-2243694d6aea)

**Comment by elral** [comment]
Unfortenutely this is a bug in the connector.
Nothing I could do here.
